### DISCUSSION TITLE
Cannot use minimal config.yaml to change streamingKey

### DISCUSSION THREAD

**Discussion by quite** [owncast/owncast#444] [Q&A] [answered]
I'm trying out owncast, running 0.0.2 in Docker. Streaming a file using `ocTestStream.sh`. It works!

Now I want to change the streamingKey, and make a minimal config.yaml (below) and pass it into the container with `-v $(pwd)/config.yaml:/app/config.yaml`

But now, the stream never comes online. Owncast and the script are running, but for viewers it remains offline. Reverting back to run without the custom config, and it works again.

I'm thinking that the custom config perhaps override stuff which it shouldn't... Ideas? @gabek 

```
instanceDetails:
  name: astream
  title: astream
  summary: "it's a stream"
  tags:
    - streaming
videoSettings:
  streamingKey: NewSecret
```
