### DISCUSSION TITLE
Artillery to load test owncast

### DISCUSSION THREAD

**Discussion by pierreozoux** [owncast/owncast#644] [Ideas]
```
config:
  target: 'https://url'
  phases:
      - duration: 3600
        arrivalRate: 500
  plugins:
    hls: {}

scenarios:
  - flow:
    - get:
        url: "/hls/2/stream.m3u8"
        hls:
          concurrency: 4
          streamSelector:
            index: all
```

We did some tests with this file. I think, from what I understand, and from 3 servers running in //, that I simulated 300 users.

I didn't look at the output metrics, didn't understand, but I did look at the stream at the same time, but all was fine.
During the event with 100 users, we had some lags.

So I'm not sure if it useful to you, but maybe it is a little seed for the next one that want to load test :)
