### DISCUSSION TITLE
offering original encoded stream as high quality

### DISCUSSION THREAD

**Discussion by novadeviator** [owncast/owncast#660] [Q&A] [answered]
I was wondering if it's possible to 'forward' or 'codec-copy' the high quality stream that is being sent as original to the server? 

As an example, I am streaming with OBS at about 3500kbps to an owncast VPS server at DigitalOcean. I would like to offer three qualities - high (an original stream), middle (transcoded to about 1200kbps and 720p) and low (800kbps and 480p). 

Essentially, I would like to avoid additional transcoding for the high quality stream since with every en/transcode there are more artifacts introduced in video and audio.

Also, I'm missing a bit more indepth view how options in config.yaml are translated to ffmpeg commandline and what are all possible options. Is this available somewhere in the sourcecode?

**Comment by novadeviator** [comment, marked as answer]
Ok, I found options that are 'read' in config.yaml in https://github.com/owncast/owncast/blob/master/config/config.go - and the option that I was looking for is called `videoPassthrough` and `audioPassthrough` and now my config looks something like
```
videoSettings:

  streamQualities:
    - medium:
      videoBitrate: 1200
      encoderPreset: veryfast
      scaledWidth: 720
    - low:
      videoBitrate: 800
      encoderPreset: veryfast
      scaledWidth: 480
    - high:
      videoPassthrough: true
      audioPassthrough: true

```
