### DISCUSSION TITLE
Compile a stream into a video (ObjectStore - S3)

### DISCUSSION THREAD

**Discussion by pierreozoux** [owncast/owncast#886] [General Owncast discussion]
This is a FYI, if you use an ObjectStore like s3, and want to compile the video in a nice mp4, I did a little script:

docker-compose if you don't have ffmpeg on the local machine:
```
version: '2'
services:
  ffmpeg:
    image: jrottenberg/ffmpeg:4.0-ubuntu
    volumes:
    - .:/data
```

the encode script:
```
#!/bin/bash -eux

cd /data

for i in `ls stream-${1}*.ts`;do echo file $i;done > ./allts
ffmpeg -f concat -i ./allts -c copy /tmp/all.ts
ffmpeg -i /tmp/all.ts -acodec copy -vcodec copy /data/final-${1}.mp4
```

And then find the stream "ID":, in the ts files, it looks like this:
```
stream-qTLAsD_Mg1617294614.ts
```

In this case, the id is `qTLAsD`

and then, start the script like this:
```
./encode.sh qTLAsD
```

And your mp4 file will be available here: `/data/final-qTLAsD.mp4`
