### ISSUE TITLE
Unable to change logo when running container version

### ISSUE THREAD

**Issue by letsautom8** [owncast/owncast#2130]
### Share your bug report, feature request, or comment.

My setup is quite simple:
docker compose
```
version: '3'

services:
 owncast:
    container_name: owncast
    image: gabekangas/owncast
    volumes:
      - ./owncast/data/:/app/data:rw
    ports:
      - 8080:8080
      - 1935:1935
```

Login to admin and change logo.
After uploading the logo, it reverted back to default owncast logo.
