### ISSUE TITLE
Workflows: Do not use pull_request_target

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2487]
### Share your bug report, feature request, or comment.

Recommendation

Do not use `pull_request_target` if the workflow doesn’t need write repository permissions and doesn’t use any repository secrets, use the `pull_request trigger` instead. If any of those privileges are required use `pull_request` and `workflow_run` combined to assign specific privileges.

Github workflows `.github/workflows/chromatic.yml` and `.github/workflows/javascript-formatting.yml` have the following trigger for starting:

```yaml
on:
  push:
    paths:
      - web/**
  pull_request_target:
    paths:
      - web/**
```

The `pull_request_target` will trigger when a new pull request is opened by any user with a target that falls in the `web` directory. This trigger will run the workflow jobs in the context of the `owncast/owncast` repository, granting them write permissions and secrets access to the target repository.

The two workflows check out the code from the remote repository code with the following job:

```yaml
- name: Checkout
    uses: actions/checkout@v3
    with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
```

After this job has completed there is an opportunity, depending on the jobs of the workflow, for malicious code to be executed in the Github action context loaded by the `pull_request_target` trigger. For example, abusing the following job, present in the two workflows:

```yaml
- name: Install Dependencies
    run: npm install
```
