### ISSUE TITLE
Owncast doesn't seem to be utilizing passthrough option

### ISSUE THREAD

**Issue by bandicootdancing** [owncast/owncast#269]
Video passthrough was mentioned in another issue here but I also didn't find this option mentioned in the config docs. OBS starts immediately dropping frames (90%+) and the stream never appears online using this config. Am I using the wrong passthrough option?

I tried going to https://github.com/gabek/owncast/blob/master/doc/configuration.md#video-quality to read about the options but I get a 404. 

```
publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/local/bin/ffmpeg
webServerPort: 8080

instanceDetails:
  name: Owncast
  title: Owncast Demo Server
  logo:
    small: /img/logo128.png
    large: /img/logo128.png

  # This is relative to the webroot, not the project root.  This is a markdown file that displays
  # extra content on below your video.  Put whatever you want in here.
  extraUserInfoFileName: "/static/content.md"

  tags:
    - music
  # https://github.com/gabek/owncast/blob/master/doc/configuration.md#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: https://github.com/gabek/owncast
videoSettings:
  # The length of a single segment of video.
  chunkLengthInSeconds: 4
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123
  # The "Stream is offline" content displayed when a stream ends.
  offlineContent: static/offline.m4v

  # Determine the bitrate of your stream variants.
  # See https://github.com/gabek/owncast/blob/master/doc/configuration.md#video-quality for details.
  streamQualities:
    - HQ:
      # Don't re-encode the video.
      videoPassthrough: true
      # Don't re-encode the audio.
      audioPassthrough: true

# Number of segments kept referenced in the HLS playlist
files:
  maxNumberInPlaylist: 4
```

**Comment by gabek** [comment]
All the documentation can be found at https://owncast.online, there may be some out of date links somewhere pointing to Github, but none of it exists on Github anymore.  If you see a link to some invalid documentation please let us know.

While technically the configuration has support for video passthrough, it proved to be unreliable so it was removed from the documentation as an officially supported option.  Because it's literally passing through the video without re-encoding we found far too many cases where the resulting video was not playable or other random incompatibilities.  Something like this is impossible to support and troubleshoot as well, because there's so many broadcasting setups out there.

In general I suggest you don't use `videoPassthrough`.  If you happen to get it working with your broadcasting and client players, then great, it's a nice win for you, but it's likely you'll run into whatever kind of weird incompatibilities you're currently seeing.

As an aside, we do support audio passthrough just because almost all broadcasting software is sending AAC and it's highly compatible with all client players, we haven't seen any kind of issues with that.

**Comment by bandicootdancing** [comment]
Ah that's unfortunate, I would hope to keep the quality as high as possible instead of encoding through obs and then again with owncast/ffmpeg. 

Now it appears to be an issue with the config.yaml file. Here's what I change it to but no matter the options the ffmpeg process appears to be applying the same settings. Here's a snippet.
```
tmp/streampipe.flv -map v:0 -c:v:0 libx264 -b:v:0 1200k -maxrate:v:0 1272k -bufsize:v:0 1440k -g:v:0 95 -x264-params:v:0 scenecut=0:open_gop=0:min-keyint=95:keyint=95 -map a:0 -c:a:0 copy
```
Here's the updated streamQualities section

```
streamQualities:
    - HQ:
      videoBitrate: 8000
      audioPassthrough: true
      encoderPreset: fast
```

**Comment by gabek** [comment]
That's concerning!  I'll take a look tonight.

**Comment by bandicootdancing** [comment]
Did quite a bit of tinkering today by changing the default encoding values in defaults.go. For some reason anything I put under streamqualities in the config gets ignored. Unfortunately, my cheap vps and local VM ramps up the CPU near 100% with a simple 3000kbps encode which is where I was hoping passthrough would help. Because the config settings were ignored I tried changing defaults.go to allow passthrough but still doesn't want to take the stream. 
```
defaultQuality := StreamQuality{
		IsVideoPassthrough: true,
		IsAudioPasstrhough: true,
	}
```
I'll probably try one last thing sometime in the future by utilizing some more powerful hardware to ensure it's not just a lack of processing while encoding.

**Comment by gabek** [comment]
Hey there!  I just checked out the release of v0.02 and config changes do seem to be respected.

Just clarifying, this is `streamQualities` under `videoSettings`, and you're using the [release version of 0.0.2](https://github.com/owncast/owncast/releases/tag/v0.0.2)?

Would you mind posting your entire config?

```
videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123

  streamQualities:
    - high:
      videoBitrate: 3200

    - medium:
      videoBitrate: 1200
```

**Comment by bandicootdancing** [comment]
Thanks, this was my config but I pasted yours into this and seems to be working. I tried the latest release as well as building. I would assume spacing errors but I also tried copying the example in the docs while only changing the bitrate values.

```
# See https://owncast.online/docs/configuration/ for more details
publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/bin/ffmpeg
webServerPort: 8080
instanceDetails:
  name: Test
  title: Test
  summary: "Test"

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - movienight

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/owncast/owncast

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123
  # The length of a single segment of video.
  chunkLengthInSeconds: 4
  # The "Stream is offline" content displayed when a stream ends.
  offlineContent: static/offline.m4v
  # See https://github.com/gabek/owncast/blob/master/doc/configuration.md#video-quality for details.
streamQualities:
    - HQ:
      videoBitrate: 5000
      audioPassthrough: true
      encoderPreset: fast
# Number of segments kept referenced in the HLS playlist
files:
  maxNumberInPlaylist: 4
```
