### ISSUE TITLE
Make admin stream title input more visible

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2933]
### Share your bug report, feature request, or comment.

In the admin, the input used to change the stream title is barely noticeable compared to the one in v0.0.13 because:
- it's tucked against the top of the page
- its unfocused state colors are very muted against the background
- the placeholder text is very light against the white input background
- ~~it doesn't have a visible "Update" button like the old one, making it less clear it's an input~~ (0.0.13 was the same for this)

I could argue that the placeholder color is too light for all inputs, but it's less of a problem for the other ones which all(?) have a label/description.

Below, and for illustration purposes only, is a proposition of how small quick style changes could help a little:

```css
.app-container .layout-header {
    padding-top: 1em;
}
.app-container .layout-header #field-streamTitle::placeholder {
    color: #252525;
}
.app-container .layout-header .field-streamTitle {
    border: 1px solid rgba(120,113,255,0.5);
}
```

![image](https://user-images.githubusercontent.com/119351153/232846689-98c42cd5-2bdc-4528-898a-9d9e48020d49.png)
![image](https://user-images.githubusercontent.com/119351153/232856473-e078b389-3c97-4df2-87d5-6e8bb485d480.png)
