### ISSUE TITLE
Video qualities don't seem to have any effect

### ISSUE THREAD

**Issue by AngusF22** [owncast/owncast#305]
I'm trying to run a videoPassthrough: true stream, but no matter what I do, or how many different qualities I set up, Owncast always calls FFMPEG with libx264 set for 1200k bitrate, with max of 1272. 

I'm running 0.0.2 in Docker.

Here's the relevant section of config.yaml:
````
streamQualities:
  - high:
    videoPassthrough: true
  - medium:
    videoBitRate: 2000
  - low:
    videoBitRate: 800
````

**Comment by gabek** [comment]
Would you mind providing your entire config file?  Also, could you point to the piece of documentation you used to configure?  We think there's some bad documentation that's making people have incorrect config files.  This happened previously with https://github.com/owncast/owncast/issues/269#issuecomment-712575974 and I'm wondering if that's what's going on with you, too.

**Comment by AngusF22** [comment]
Ahhh, that could be it after all - I see the missing indentation under that issue. Let me check that and report back. In the meantime, my config as requested:

````
# See https://owncast.online/docs/configuration/ for more details

instanceDetails:
  name: Owncast
  title: Owncast
  summary: "This is brief summary of whom you are or what your stream is. You can read more about it at owncast.online.  You can edit this description in your config file."

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - music
    - software
    - streaming

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/owncast/owncast
    - platform: mastodon
      url: http://mastodon.something/owncast

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: test123456

streamQualities:
  - high:
    videoPassthrough: true
  - medium:
    videoBitRate: 2000
  - low:
    videoBitRate: 800


````
