### ISSUE TITLE
Stream qualities config seems to not work

### ISSUE THREAD

**Issue by muesli** [owncast/owncast#343]
I've configured three different stream qualities in my `config.yaml`, but it seems like the settings have no effect, as I can see ffmpeg process being spawned with the default 1200kbps.

Here's my config:

```yaml
instanceDetails:
...

videoSettings:
  streamingKey: ...

  streamQualities:
    - low:
        videoBitrate: 800
        encoderPreset: veryfast

    - medium:
        videoBitrate: 1600
        encoderPreset: veryfast

    - high:
        videoBitrate: 2400
        encoderPreset: veryfast

ffmpegPath: /usr/bin/ffmpeg
```
