### ISSUE TITLE
Docker container Nvidia encoding

### ISSUE THREAD

**Issue by Khyretos** [owncast/owncast#3930]
### Share your bug report, feature request, or comment.

For some reason i can select the VA-API in the dropdown but it does not work

![image](https://github.com/user-attachments/assets/feb37ccb-5ba1-4087-85d6-67a7bae0ba34)

i get this in the log:
```shell
time="2024-09-22T15:15:01Z" level=error msg="[AVHWDeviceContext @ 0x76284a44ed80] Failed to initialise VAAPI connection: -1 (unknown libva error)."
time="2024-09-22T15:15:01Z" level=error msg="Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': I/O error"
time="2024-09-22T15:15:01Z" level=info msg="Inbound stream disconnected."
time="2024-09-22T15:15:01Z" level=error msg="unable to write rtmp packet io: read/write on closed pipe"
time="2024-09-22T15:15:01Z" level=error msg="transcoding error. look at data/logs/transcoder.log to help debug. your copy of ffmpeg may not support your selected codec of h264_vaapi https://owncast.online/docs/codecs/"
time="2024-09-22T15:15:03Z" level=info msg="Inbound stream connected from xx.xx.xx.xx:xxxx"
time="2024-09-22T15:15:03Z" level=info msg="Processing video using codec VA-API with 1 output qualities configured."
time="2024-09-22T15:15:03Z" level=error msg="[AVHWDeviceContext @ 0x7cfb538eed80] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)"
```
this is my docker image:
```yaml
services:
  owncast:
    image: ghcr.io/owncast/owncast:nightly
    container_name: owncast
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 1935:1935
    volumes:
      - ./owncast:/app/data
      - ./test:/ffmpeg
    runtime: nvidia
    devices:
#      - /dev/nvidia-caps:/dev/nvidia-caps
#      - /dev/nvidia0:/dev/nvidia0
#      - /dev/nvidiactl:/dev/nvidiactl
#      - /dev/nvidia-modeset:/dev/nvidia-modeset
#      - /dev/nvidia-uvm:/dev/nvidia-uvm
#      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
```

i know my device is readable through docker, my jellyfin container uses it and my portainer container as well.
and i added the 'runtime' and 'devices' parameters because i saw some issues related to it but nothing works. i can only encode in x264. i am trying to use NVENC, H.264 to encode the stream.

I just want to see if the latency is less because right now the delay is about 10 seconds. i dont know if there are some tips to get less delay.

a bit of help would be appreciated. thanks in advance.
