### ISSUE TITLE
Enable Intel GPU hardware acceleration support (without needing to enter the docker container)

### ISSUE THREAD

**Issue by Khyretos** [owncast/owncast#4366]
### Share your bug report, feature request, or comment.

Hey,

maybe i am wrong but for me to enable hardware support for my intel gpu (A580) i need to run the following commands:

enter the image:
`sudo docker exec -it owncast /bin/sh`

install the needed packages for hardware support:
`apk add --upgrade intel-media-driver
apk add --upgrade onevpl-intel-gpu --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/`

then i can use VA-API hardware encoding.
but if for some reason i need to restart my server or image it is lost and i have to run the commands again.

Is there a way for it to be always enabled? or am i just using the wrong image?
currently this is my compose file
```yaml
services:
  owncast:
    image: ghcr.io/owncast/owncast:nightly
    container_name: owncast
    restart: unless-stopped
    ports:
      - 1935:1935
    volumes:
      - ./owncast:/app/data
    devices:
      - /dev/dri
```

running the commands makes it possible to only use Vaapi, i cannot use QSV tho.
i got the commands from another bug report i saw here in github so i tried it out and it worked. 
i dont know if there is an intel image out there that i have maybe overlooked though.

if there is a way to make it completely compatible with my arc gpu it would be appreciated.
