### ISSUE TITLE
Web Player Uses Lowest Bitrate

### ISSUE THREAD

**Issue by graywolf336** [owncast/owncast#50]
When testing, it appears that the web player is using the lowest bitrate even though I have ample bandwidth for the high quality video

**Comment by gabek** [comment]
I popped your stream into the hls validator, attaching it here just for reference.  Looking at it to see if there's anything in it that would point to why that bitrate is being ignored.  (Server host name redacted in file).

[graywolf.txt](https://github.com/gabek/owncast/files/4908927/graywolf.txt)

**Comment by gabek** [comment]
This is my current video config on goth.land:

```
    - high:
      videoBitrate: 1200

    - low:
      videoBitrate: 700
      scaledWidth: 600
      encoderPreset: superfast
```

And the high quality is being played on the web.  What does your config look like?

**Comment by graywolf336** [comment]
Here is my current config

```
  streamQualities:
    - full:
      videoPassthrough: false
      audioPassthrough: true

    - low:
      videoBitrate: 700
      scaledWidth: 600
      audioPassthrough: true
      encoderPreset: superfast
```

**Comment by gabek** [comment]
I just threw your config in and I got this resulting master playlist, with the two variants.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2996224,RESOLUTION=1192x746
0/stream.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=950224,RESOLUTION=600x376,CODECS="avc1.64001e,mp4a.40.2"
1/stream.m3u8
```

In playback it's pulling variant 0, as it should be.
![image](https://user-images.githubusercontent.com/414923/87367059-e89d1e80-c52e-11ea-9fc7-63d0b3fb73a3.png)

So something is different with what's being generated.  Could you take a look at your master `stream.m3u8` playlist and see if there's anything in there that could be explaining it?

**Comment by gabek** [comment]
As an aside, we should add a quality selector.  I'll wait until the JS updates, but after that it would be a good addition.

https://github.com/silvermine/videojs-quality-selector

**Comment by graywolf336** [comment]
Yeah, I'll take a look later today and provide it

**Comment by gabek** [comment]
As an aside that videojs quality selector doesn't support HLS variants anyway, it's just for inline video sources.  Lame.

**Comment by gabek** [comment]
I've been trying to keep an eye on if this happens for me.  I've seen it drop qualities, and sometimes stay there for a few minutes, but it always makes its way back up as I'd expect.

Another thing to test, can you open Quicktime or VLC or something and hit /hls/0/stream.m3u8 directly? (I'm assuming that's your high quality).  Does playing just that stream directly play without issue?  If you start seeing buffering or something then that would explain why the web player is switching.

**Comment by mattdsteele** [comment]
One more data point: with my own videojs implementation (I'm embedding the stream on my own website) appears to be using the right stream for the amount of bandwidth it's got (I've been testing with Edge's built-in network throttling to "Fast 3G" and it goes to my lower-quality stream.

My videojs setup:

```js
  const player = videojs(video, {
    controls: true,
    autoplay: true,
    preload: 'auto',
    liveui: true,
    liveTracker: {
      trackingThreshold: 30,
      liveTolerance: 5,
    },
    fluid: true,
    fill: true,
    responsive: true,
  });
  player.src({ type: 'application/x-mpegURL', src: videoSrc });
};
```

And my stream config:

```
  streamQualities:
    # Transcode the video to a lower bitrate and resize
    - low:
      # Higher the bitrate, the better it looks, but it requires more bandwidth to consume.
      videoBitrate: 400
      # Resize the width to something smaller.  scaledHeight is also an option.  Don't use both at once
      # unless you want to chang the aspect ratio of your video.
      scaledWidth: 600
      # Don't re-encode the audio.
      audioPassthrough: true
      # The slower the preset the higher quality the video is.
      # Select a preset from https://trac.ffmpeg.org/wiki/Encode/H.264
      # "superfast" and "ultrafast" are generally not recommended since they look bad.
      encoderPreset: veryfast
    - medium:
      videoBitrate: 800
      encoderPreset: fast
```

**Comment by gabek** [comment]
@graywolf336 Were you able to track anything down about what you were seeing?  If this is continuing to happen it's a pretty big deal and I want to make sure it's resolved for sure.

**Comment by graywolf336** [comment]
I have not had a chance yet. I'll do my best to put up the server again this weekend and get two streams in on Sunday.

**Comment by gabek** [comment]
If I had to guess this is why HLS players are switching from the high to the lower bitrate.  It's basically saying "Hey you said this variant is going to use X amount of bandwidth, but it's using more than that, so I'm going to use another one".

![image](https://user-images.githubusercontent.com/414923/89137530-3c2ad880-d4ed-11ea-9eff-df3542bebb61.png)

I'm going to look into this.

**Comment by gabek** [comment]
I've had a branch laying around that addresses this exact thing, but I never really went further with it because I wasn't seeing real-world issues, and I was afraid adding more variables was just adding complexity, but I'm going to get those changes tested.

I'm still not sure why some circumstances are really effected, like for @graywolf336 it seems to 100% of the time, but for me I've never run into it actually effecting the output quality and player's functionality.

**Comment by gabek** [comment]
@graywolf336 Out of curiosity, what bitrate audio/audio settings are you sending to your instance?  I have a new hypothesis. Because in your config you're passing along audio without transcoding:

transcoded video bitrate + non-transcoded audio source bitrate > the max bandwidth we say the stream is.

And maybe the reason you're seeing this and I'm not is because the audio you're sending is higher than what I send, therefore your final variant stream is higher than what it's advertised to be and is pushed over the edge.

Could you try turning off `audioPassthrough`?

This is just a hypothesis that came to mind when I was thinking about bitrate variants peaking higher than they're advertised to be.  Audio counts against that.

**Comment by graywolf336** [comment]
Yeah, I can try that Wednesday night and see what happens. I'll look on Wednesday and see what audio bitrate we are sending. I can't replicate it until Wednesday, so I apologize for the delay

**Comment by gabek** [comment]
I pushed a branch with some logging thrown in there.  While looking around I found a `limitRenditionByPlayerDimensions` option on player.  I turned it off in the `gek/videojs-logging` branch just to see if it makes a difference.  But given I've seen the playback drop to the lower variant in Quicktime directly I doubt this web player option is to blame.

But maybe we can get at least some idea of why it's selecting what it is.

**Comment by gabek** [comment]
Not sure if this is related, or helpful, but I updated video.js and moved to a much more recent version of its http streaming library in #133.  It's in master now.

**Comment by graywolf336** [comment]
I'll update my instance and see if it still happens this Wednesday evening.

**Comment by muesli** [comment]
Any update on this, @graywolf336?

**Comment by graywolf336** [comment]
I need to update and try the latest. My setup doesn't use the UI very much, so I have to intentional watch and pay attention. I'll try to pay attention this weekend.

**Comment by mattdsteele** [comment]
One more data point: while streaming yesterday I noticed it definitely preferred the low quality stream. I wasn't focused on testing so didn't get to do much analysis; but it's an indication that this may still be sporadically cropping up.

My config:

```yaml
  streamQualities:
    - high:
      videoBitrate: 2500
      encoderPreset: veryfast
      framerate: 30
    - low:
      videoBitrate: 300
      encoderPreset: veryfast
      framerate: 30
```
