### ISSUE TITLE
Update S3 documentation 

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#555]
* Add example of what it actually looks like to configure it in `config.yaml`.
* Add detailed CORS instructions for Digital Ocean spaces.

**Comment by kaffeeringe** [comment]
* Add detailed instructions for Strato HiDrive S3

**Comment by kaffeeringe** [comment]
Strato HiDrive S3. This connects to the bucket:
```
s3:
 enabled: true
 accessKey: 123
 secret: ABC
 region: eu-central-1
 endpoint: https://s3.hidrive.strato.com
 servingEndpoint: https://s3.hidrive.strato.com
 bucket: owncast
```
But it doesn't play from there. I only get to see a thumbnail. I think the servingEndpoint isn't correct. But I don't have any other URL.
