### ISSUE TITLE
Make transparency of message bubbles overridable via CSS

### ISSUE THREAD

**Issue by aral** [owncast/owncast#910]
## Use case

I want to chroma key the chat view into my video.

## The problem

The colours are randomly chosen for each person and use inline styles with the alpha hardcoded so it is impossible to override them (and keep the unique colours) using just CSS.

## The proposed solution 

Use a CSS variable for the alpha value of the generated colour.

So, for example, instead of the colour being, e.g,

```css
rgba(ff,00,00, 0.5)
```

We would generate:

```css
rgba(ff, 00, 00, var(--message-background-alpha))
```

In the CSS, the initial value of alpha can be set to some default value. e.g., 

```css
:root {
--message-background-alpha: 0.3;
}
```

And then anyone can override that in their own stylesheet, for example, they can set:

```css
:root {
  --message-background-alpha: 1.0;
}
```

To have the backgrounds be opaque and thus work well in a chroma key.
